SHELL := /bin/bash

LOCAL_CONFIG ?= .make.env
LOCAL_CONFIG_PATH := $(abspath $(LOCAL_CONFIG))
REPO_ROOT := $(shell git rev-parse --show-toplevel 2>/dev/null)
ifneq ($(words $(LOCAL_CONFIG)),1)
$(error LOCAL_CONFIG must be a single path without whitespace)
endif
ifneq ($(wildcard $(LOCAL_CONFIG)),)
ifeq ($(shell test -L '$(LOCAL_CONFIG)' && echo yes),yes)
$(error Refusing to include symlinked LOCAL_CONFIG $(LOCAL_CONFIG))
endif
ifeq ($(REPO_ROOT),)
-include $(LOCAL_CONFIG)
else
LOCAL_CONFIG_REL := $(patsubst $(REPO_ROOT)/%,%,$(LOCAL_CONFIG_PATH))
ifeq ($(LOCAL_CONFIG_REL),$(LOCAL_CONFIG_PATH))
-include $(LOCAL_CONFIG)
else ifeq ($(shell git -C '$(REPO_ROOT)' check-ignore -q -- '$(LOCAL_CONFIG_REL)' && echo yes),yes)
-include $(LOCAL_CONFIG)
else
$(error Refusing to include unignored repo local config $(LOCAL_CONFIG_REL); add it to .gitignore or use LOCAL_CONFIG outside the repo)
endif
endif
endif
export OPEN_SANDBOX_API_KEY

RESOURCE_GROUP ?= rg-opensandbox-kata
SUBSCRIPTION_ID ?=
LOCATION ?= eastus
AKS_NAME ?= osb-kata-aks
ACR_NAME ?=
NODE_VM_SIZE ?= Standard_D4s_v3
NODE_COUNT ?= 3
ASSIGN_ACR_PULL_ROLE ?= true
ACR_ADMIN_USER_ENABLED ?= false
OPEN_SANDBOX_NAMESPACE ?= opensandbox
OPEN_SANDBOX_CONTROLLER_VERSION ?= 0.1.0
OPEN_SANDBOX_CLI_VERSION ?= 0.1.1
SERVER_IMAGE_NAME ?= opensandbox-kata-server
SERVER_IMAGE_TAG ?= latest
SANDBOX_IMAGE ?= python:3.12-slim
SERVER_PORT ?= 8080

ACR_LOGIN_SERVER := $(ACR_NAME).azurecr.io
SERVER_IMAGE := $(ACR_LOGIN_SERVER)/$(SERVER_IMAGE_NAME):$(SERVER_IMAGE_TAG)

CONFIGURED_TARGETS := all print-config infra-deploy aks-credentials acr-login image-build image-push controller-install k8s-deploy smoke-test cli-smoke-test
INTERNAL_TARGETS := $(addprefix _,$(CONFIGURED_TARGETS))
MAKEFILE_PATH := $(abspath $(firstword $(MAKEFILE_LIST)))

.PHONY: $(CONFIGURED_TARGETS) $(INTERNAL_TARGETS) local-config check-tools check-smoke-tools check-vars check-api-key status clean-k8s infra-delete

define configured_target
$1: local-config
	@$$(MAKE) --no-print-directory -f "$$(MAKEFILE_PATH)" LOCAL_CONFIG="$$(LOCAL_CONFIG)" _$1
endef

define reject_env_var
@if [ "$(origin $(1))" = "environment" ]; then echo "For $(2), pass $(1) explicitly on the make command line or store it in $(LOCAL_CONFIG); environment values are not accepted"; exit 1; fi
endef

define require_cli_or_config
@if [ "$(origin $(1))" != "command line" ] && ! grep -Eq '^(export[[:space:]]+)?$(1)[[:space:]]*([?:+]?=|=)' "$(LOCAL_CONFIG)" 2>/dev/null; then echo "$(LOCAL_CONFIG) is missing $(1); run make local-config or pass $(1) explicitly on the make command line"; exit 1; fi
endef

define confirm_var
@if [ "$(CONFIRM_$(1))" != "$($(1))" ]; then echo "Set CONFIRM_$(1)=$($(1)) to $(2)"; exit 1; fi
endef

$(foreach target,$(CONFIGURED_TARGETS),$(eval $(call configured_target,$(target))))

_all: check-tools check-api-key _infra-deploy _aks-credentials _acr-login _image-build _image-push _controller-install _k8s-deploy _smoke-test

local-config:
	@set -euo pipefail; \
		file="$(LOCAL_CONFIG)"; \
		case "$$file" in *[!A-Za-z0-9_./-]*) echo "LOCAL_CONFIG contains unsupported characters; use letters, numbers, dot, slash, underscore, or dash"; exit 1 ;; esac; \
		if [ -L "$$file" ]; then echo "Refusing to use symlinked LOCAL_CONFIG $$file"; exit 1; fi; \
		repo_root=$$(git rev-parse --show-toplevel 2>/dev/null || true); \
		if [ -n "$$repo_root" ]; then \
			case "$$file" in /*) config_path="$$file" ;; *) config_path="$$PWD/$$file" ;; esac; \
			case "$$config_path" in "$$repo_root"/*) \
				rel_path="$${config_path#"$$repo_root"/}"; \
				if git -C "$$repo_root" ls-files --error-unmatch -- "$$rel_path" >/dev/null 2>&1; then \
					echo "Refusing to write local config to tracked file $$rel_path"; \
					exit 1; \
				fi; \
				if ! git -C "$$repo_root" check-ignore -q -- "$$rel_path"; then \
					echo "Refusing to write secrets to unignored repo path $$rel_path; add it to .gitignore or use LOCAL_CONFIG outside the repo"; \
					exit 1; \
				fi; \
			;; esac; \
		fi; \
		changed=0; \
		if [ ! -f "$$file" ]; then \
			umask 077; \
			{ \
				echo '# Local environment config generated by make local-config'; \
				echo '# This file is intentionally ignored by git.'; \
			} > "$$file"; \
			changed=1; \
		fi; \
		chmod 600 "$$file"; \
		suffix=$$(date +%m%d%H%M | tr -d '\n'); \
		acr_suffix=$$(date +%m%d%H%M%S | tr -d '\n')$$(od -An -tx1 -N3 /dev/urandom | tr -d ' \n'); \
		api_key=$$(od -An -tx1 -N32 /dev/urandom | tr -d ' \n'); \
		current_subscription=$$(az account show --query id -o tsv 2>/dev/null || true); \
		value_for() { \
			origin="$$1"; \
			current="$$2"; \
			fallback="$$3"; \
			case "$$origin" in environment|"command line") printf '%s' "$$current" ;; *) printf '%s' "$$fallback" ;; esac; \
		}; \
		add_if_missing() { \
			key="$$1"; \
			line="$$2"; \
			if ! grep -Eq "^(export[[:space:]]+)?$$key[[:space:]]*([?:+]?=|=)" "$$file"; then \
				printf '%s\n' "$$line" >> "$$file"; \
				changed=1; \
			fi; \
		}; \
		location=$$(value_for '$(origin LOCATION)' '$(LOCATION)' 'eastus'); \
		resource_group=$$(value_for '$(origin RESOURCE_GROUP)' '$(RESOURCE_GROUP)' "rg-opensandbox-kata-$$suffix"); \
		subscription_id=$$(value_for '$(origin SUBSCRIPTION_ID)' '$(SUBSCRIPTION_ID)' "$$current_subscription"); \
		aks_name=$$(value_for '$(origin AKS_NAME)' '$(AKS_NAME)' "osb-kata-$$suffix"); \
		acr_name=$$(value_for '$(origin ACR_NAME)' '$(ACR_NAME)' "osbkata$$acr_suffix"); \
		api_key=$$(value_for '$(origin OPEN_SANDBOX_API_KEY)' '$(OPEN_SANDBOX_API_KEY)' "$$api_key"); \
		add_if_missing LOCATION "LOCATION ?= $$location"; \
		add_if_missing RESOURCE_GROUP "RESOURCE_GROUP ?= $$resource_group"; \
		if [ -n "$$subscription_id" ]; then add_if_missing SUBSCRIPTION_ID "SUBSCRIPTION_ID ?= $$subscription_id"; fi; \
		add_if_missing AKS_NAME "AKS_NAME ?= $$aks_name"; \
		add_if_missing ACR_NAME "ACR_NAME ?= $$acr_name"; \
		add_if_missing NODE_VM_SIZE 'NODE_VM_SIZE ?= Standard_D4s_v3'; \
		add_if_missing NODE_COUNT 'NODE_COUNT ?= 3'; \
		add_if_missing ASSIGN_ACR_PULL_ROLE 'ASSIGN_ACR_PULL_ROLE ?= true'; \
		add_if_missing ACR_ADMIN_USER_ENABLED 'ACR_ADMIN_USER_ENABLED ?= false'; \
		add_if_missing OPEN_SANDBOX_NAMESPACE 'OPEN_SANDBOX_NAMESPACE ?= opensandbox'; \
		add_if_missing OPEN_SANDBOX_CONTROLLER_VERSION 'OPEN_SANDBOX_CONTROLLER_VERSION ?= 0.1.0'; \
		add_if_missing OPEN_SANDBOX_CLI_VERSION 'OPEN_SANDBOX_CLI_VERSION ?= 0.1.1'; \
		add_if_missing SERVER_IMAGE_NAME 'SERVER_IMAGE_NAME ?= opensandbox-kata-server'; \
		add_if_missing SERVER_IMAGE_TAG 'SERVER_IMAGE_TAG ?= latest'; \
		add_if_missing SANDBOX_IMAGE 'SANDBOX_IMAGE ?= python:3.12-slim'; \
		add_if_missing SERVER_PORT 'SERVER_PORT ?= 8080'; \
		add_if_missing OPEN_SANDBOX_API_KEY "OPEN_SANDBOX_API_KEY ?= $$api_key"; \
		if ! grep -Eq '^export[[:space:]]+OPEN_SANDBOX_API_KEY([[:space:]]|$$)' "$$file"; then \
			echo 'export OPEN_SANDBOX_API_KEY' >> "$$file"; \
			changed=1; \
		fi; \
		if [ "$$changed" -eq 1 ]; then \
			echo "Updated $$file"; \
		else \
			echo "Using $$file"; \
		fi

_print-config:
	@echo "LOCAL_CONFIG=$(LOCAL_CONFIG)"
	@echo "RESOURCE_GROUP=$(RESOURCE_GROUP)"
	@echo "SUBSCRIPTION_ID=$(SUBSCRIPTION_ID)"
	@echo "LOCATION=$(LOCATION)"
	@echo "AKS_NAME=$(AKS_NAME)"
	@echo "ACR_NAME=$(ACR_NAME)"
	@echo "NODE_VM_SIZE=$(NODE_VM_SIZE)"
	@echo "NODE_COUNT=$(NODE_COUNT)"
	@echo "ASSIGN_ACR_PULL_ROLE=$(ASSIGN_ACR_PULL_ROLE)"
	@echo "ACR_ADMIN_USER_ENABLED=$(ACR_ADMIN_USER_ENABLED)"
	@echo "OPEN_SANDBOX_NAMESPACE=$(OPEN_SANDBOX_NAMESPACE)"
	@echo "OPEN_SANDBOX_CLI_VERSION=$(OPEN_SANDBOX_CLI_VERSION)"
	@echo "SERVER_IMAGE=$(SERVER_IMAGE)"

check-tools:
	@command -v az >/dev/null || (echo "az is required"; exit 1)
	@command -v kubectl >/dev/null || (echo "kubectl is required"; exit 1)
	@command -v helm >/dev/null || (echo "helm is required"; exit 1)
	@command -v docker >/dev/null || (echo "docker is required"; exit 1)
	@command -v python3 >/dev/null || (echo "python3 is required"; exit 1)
	@command -v curl >/dev/null || (echo "curl is required"; exit 1)

check-smoke-tools:
	@command -v kubectl >/dev/null || (echo "kubectl is required"; exit 1)
	@command -v python3 >/dev/null || (echo "python3 is required"; exit 1)
	@command -v curl >/dev/null || (echo "curl is required"; exit 1)

check-vars:
	@test -n "$(ACR_NAME)" || (echo "ACR_NAME is required and must be globally unique"; exit 1)
	@if [ "$(ASSIGN_ACR_PULL_ROLE)" = "false" ] && [ "$(ACR_ADMIN_USER_ENABLED)" != "true" ]; then \
		echo "ACR_ADMIN_USER_ENABLED=true is required when ASSIGN_ACR_PULL_ROLE=false"; \
		exit 1; \
	fi

check-api-key:
	@test -n "$${OPEN_SANDBOX_API_KEY}" || (echo "OPEN_SANDBOX_API_KEY is required"; exit 1)

_infra-deploy: check-vars
	az group create --name "$(RESOURCE_GROUP)" --location "$(LOCATION)"
	az deployment group create \
		--resource-group "$(RESOURCE_GROUP)" \
		--template-file infra/main.bicep \
		--parameters aksName="$(AKS_NAME)" acrName="$(ACR_NAME)" location="$(LOCATION)" nodeVmSize="$(NODE_VM_SIZE)" nodeCount=$(NODE_COUNT) assignAcrPullRole=$(ASSIGN_ACR_PULL_ROLE) acrAdminUserEnabled=$(ACR_ADMIN_USER_ENABLED)

_aks-credentials:
	az aks get-credentials --resource-group "$(RESOURCE_GROUP)" --name "$(AKS_NAME)" --overwrite-existing

_acr-login: check-vars
	@az acr show --name "$(ACR_NAME)" --query loginServer -o tsv >/dev/null

_image-build: check-vars
	docker build -t "$(SERVER_IMAGE)" -f examples/opensandbox-kata/server.Dockerfile .

_image-push: check-vars
	@set -euo pipefail; \
		login_server=$$(az acr show --name "$(ACR_NAME)" --query loginServer -o tsv); \
		test -n "$$login_server"; \
		test "$(ACR_LOGIN_SERVER)" = "$$login_server"; \
		docker_config=$$(mktemp -d); \
		chmod 700 "$$docker_config"; \
		trap 'DOCKER_CONFIG="$$docker_config" docker logout "'"$$login_server"'" >/dev/null 2>&1 || true; rm -rf "$$docker_config"' EXIT; \
		token=$$(az acr login --name "$(ACR_NAME)" --expose-token --query accessToken -o tsv); \
		test -n "$$token"; \
		DOCKER_CONFIG="$$docker_config" docker login "$$login_server" --username 00000000-0000-0000-0000-000000000000 --password-stdin <<< "$$token"; \
		DOCKER_CONFIG="$$docker_config" docker push "$(SERVER_IMAGE)"

_controller-install:
	helm upgrade --install opensandbox-controller \
		https://github.com/opensandbox-group/OpenSandbox/releases/download/helm/opensandbox-controller/$(OPEN_SANDBOX_CONTROLLER_VERSION)/opensandbox-controller-$(OPEN_SANDBOX_CONTROLLER_VERSION).tgz \
		--namespace opensandbox-system \
		--create-namespace
	kubectl wait --for=condition=Established crd/batchsandboxes.sandbox.opensandbox.io --timeout=180s
	kubectl wait --for=condition=Established crd/pools.sandbox.opensandbox.io --timeout=180s
	kubectl wait --for=condition=ready pod -l control-plane=controller-manager -n opensandbox-system --timeout=180s
	kubectl get runtimeclass kata-vm-isolation

_k8s-deploy: check-vars check-api-key
	kubectl create namespace "$(OPEN_SANDBOX_NAMESPACE)" --dry-run=client -o yaml | kubectl apply -f -
	kubectl -n "$(OPEN_SANDBOX_NAMESPACE)" create serviceaccount opensandbox-server --dry-run=client -o yaml | kubectl apply -f -
	kubectl -n "$(OPEN_SANDBOX_NAMESPACE)" create secret generic opensandbox-server \
		--from-literal=api-key="$${OPEN_SANDBOX_API_KEY}" \
		--dry-run=client -o yaml | kubectl apply -f -
	@if [ "$(ASSIGN_ACR_PULL_ROLE)" = "false" ] && [ "$(ACR_ADMIN_USER_ENABLED)" = "true" ]; then \
		set -euo pipefail; \
		password=$$(az acr credential show --name "$(ACR_NAME)" --query 'passwords[0].value' -o tsv); \
		test -n "$$password"; \
		kubectl delete secret acr-pull -n "$(OPEN_SANDBOX_NAMESPACE)" --ignore-not-found; \
		printf '%s' "$$password" | REGISTRY="$(ACR_LOGIN_SERVER)" USERNAME="$(ACR_NAME)" NAMESPACE="$(OPEN_SANDBOX_NAMESPACE)" python3 -c 'import base64,json,os,sys; u=os.environ["USERNAME"]; p=sys.stdin.read(); r=os.environ["REGISTRY"]; ns=os.environ["NAMESPACE"]; auth=base64.b64encode(f"{u}:{p}".encode()).decode(); cfg={"auths":{r:{"username":u,"password":p,"auth":auth}}}; data=base64.b64encode(json.dumps(cfg,separators=(",",":")).encode()).decode(); print(f"apiVersion: v1\nkind: Secret\nmetadata:\n  name: acr-pull\n  namespace: {ns}\ntype: kubernetes.io/dockerconfigjson\ndata:\n  .dockerconfigjson: {data}\n")' | kubectl create -f -; \
		kubectl -n "$(OPEN_SANDBOX_NAMESPACE)" patch serviceaccount opensandbox-server \
			--type merge \
			--patch '{"imagePullSecrets":[{"name":"acr-pull"}]}'; \
	fi
	sed \
		-e 's|__NAMESPACE__|$(OPEN_SANDBOX_NAMESPACE)|g' \
		examples/opensandbox-kata/config/sandbox.toml | kubectl -n "$(OPEN_SANDBOX_NAMESPACE)" create configmap opensandbox-server-config \
		--from-file=sandbox.toml=/dev/stdin \
		--dry-run=client -o yaml | kubectl apply -f -
	sed \
		-e 's|__SERVER_IMAGE__|$(SERVER_IMAGE)|g' \
		-e 's|__NAMESPACE__|$(OPEN_SANDBOX_NAMESPACE)|g' \
		examples/opensandbox-kata/k8s/opensandbox-server.yaml | kubectl apply -f -
	kubectl rollout restart deployment/opensandbox-server -n "$(OPEN_SANDBOX_NAMESPACE)"
	kubectl rollout status deployment/opensandbox-server -n "$(OPEN_SANDBOX_NAMESPACE)" --timeout=180s

_smoke-test:
	@set -e; \
		kubectl -n "$(OPEN_SANDBOX_NAMESPACE)" port-forward svc/opensandbox-server $(SERVER_PORT):8080 >/tmp/opensandbox-kata-port-forward.log 2>&1 & \
		port_forward_pid=$$!; \
		trap 'kill $$port_forward_pid >/dev/null 2>&1 || true' EXIT; \
		for i in {1..30}; do curl -fsS http://localhost:$(SERVER_PORT)/health >/dev/null 2>&1 && break || sleep 1; done; \
		curl -fsS http://localhost:$(SERVER_PORT)/health >/dev/null; \
		smoke_api_key=$$(kubectl -n "$(OPEN_SANDBOX_NAMESPACE)" get secret opensandbox-server -o jsonpath='{.data.api-key}' 2>/dev/null | base64 -d 2>/dev/null || true); \
		smoke_api_key="$${smoke_api_key:-$${OPEN_SANDBOX_API_KEY}}"; \
		test -n "$$smoke_api_key" || (echo "OPEN_SANDBOX_API_KEY is required, or deploy opensandbox-server with make k8s-deploy first"; exit 1); \
		python3 -m venv .venv; \
		. .venv/bin/activate; \
		pip install -q -r examples/opensandbox-kata/requirements.txt; \
		OPEN_SANDBOX_DOMAIN=localhost:$(SERVER_PORT) OPEN_SANDBOX_API_KEY="$$smoke_api_key" SANDBOX_IMAGE="$(SANDBOX_IMAGE)" VERIFY_KATA_WITH_KUBECTL=1 OPEN_SANDBOX_NAMESPACE="$(OPEN_SANDBOX_NAMESPACE)" python examples/opensandbox-kata/app.py

_cli-smoke-test: check-smoke-tools
	@set -euo pipefail; \
		port_forward_log=$$(mktemp); \
		kubectl -n "$(OPEN_SANDBOX_NAMESPACE)" port-forward svc/opensandbox-server $(SERVER_PORT):8080 >"$$port_forward_log" 2>&1 & \
		port_forward_pid=$$!; \
		trap 'kill $$port_forward_pid >/dev/null 2>&1 || true; rm -f "$$port_forward_log"' EXIT; \
		for i in {1..30}; do \
			kill -0 $$port_forward_pid >/dev/null 2>&1 || (cat "$$port_forward_log"; exit 1); \
			health=$$(curl -fsS http://localhost:$(SERVER_PORT)/health 2>/dev/null || true); \
			HEALTH="$$health" python3 -c 'import json, os, sys; sys.exit(0 if json.loads(os.environ["HEALTH"]).get("status") == "healthy" else 1)' >/dev/null 2>&1 && break; \
			sleep 1; \
		done; \
		kill -0 $$port_forward_pid >/dev/null 2>&1 || (cat "$$port_forward_log"; exit 1); \
		health=$$(curl -fsS http://localhost:$(SERVER_PORT)/health); \
		HEALTH="$$health" python3 -c 'import json, os, sys; sys.exit(0 if json.loads(os.environ["HEALTH"]).get("status") == "healthy" else 1)' || (echo "Unexpected opensandbox-server health response: $$health"; exit 1); \
		cli_api_key=$$(kubectl -n "$(OPEN_SANDBOX_NAMESPACE)" get secret opensandbox-server -o jsonpath='{.data.api-key}' 2>/dev/null | base64 -d 2>/dev/null || true); \
		cli_api_key="$${cli_api_key:-$${OPEN_SANDBOX_API_KEY:-}}"; \
		test -n "$$cli_api_key" || (echo "OPEN_SANDBOX_API_KEY is required, or deploy opensandbox-server with make k8s-deploy first"; exit 1); \
		python3 -m venv .venv; \
		. .venv/bin/activate; \
		pip install -q -r examples/opensandbox-kata/requirements.txt opensandbox-cli==$(OPEN_SANDBOX_CLI_VERSION); \
		OPEN_SANDBOX_DOMAIN=localhost:$(SERVER_PORT) OPEN_SANDBOX_PROTOCOL=http OPEN_SANDBOX_API_KEY="$$cli_api_key" OPEN_SANDBOX_USE_SERVER_PROXY=true SANDBOX_IMAGE="$(SANDBOX_IMAGE)" VERIFY_KATA_WITH_KUBECTL=1 OPEN_SANDBOX_NAMESPACE="$(OPEN_SANDBOX_NAMESPACE)" OSB_BIN="$$(command -v osb)" bash examples/opensandbox-kata-cli/osb-cli-smoke.sh

status:
	kubectl get runtimeclass
	kubectl get pods -n opensandbox-system
	kubectl get pods -n "$(OPEN_SANDBOX_NAMESPACE)" -o wide
	kubectl get batchsandboxes -n "$(OPEN_SANDBOX_NAMESPACE)" || true

clean-k8s:
	$(call reject_env_var,AKS_NAME,cleanup)
	$(call reject_env_var,RESOURCE_GROUP,cleanup)
	$(call reject_env_var,SUBSCRIPTION_ID,cleanup)
	$(call reject_env_var,OPEN_SANDBOX_NAMESPACE,cleanup)
	$(call require_cli_or_config,AKS_NAME)
	$(call require_cli_or_config,RESOURCE_GROUP)
	$(call require_cli_or_config,SUBSCRIPTION_ID)
	$(call require_cli_or_config,OPEN_SANDBOX_NAMESPACE)
	$(call confirm_var,AKS_NAME,clean Kubernetes resources)
	$(call confirm_var,RESOURCE_GROUP,clean Kubernetes resources)
	$(call confirm_var,SUBSCRIPTION_ID,clean Kubernetes resources)
	$(call confirm_var,OPEN_SANDBOX_NAMESPACE,clean Kubernetes resources)
	@set -euo pipefail; \
		expected_kubeconfig=$$(mktemp); \
		trap 'rm -f "$$expected_kubeconfig"' EXIT; \
		az aks get-credentials --resource-group "$(RESOURCE_GROUP)" --name "$(AKS_NAME)" --subscription "$(SUBSCRIPTION_ID)" --file "$$expected_kubeconfig" --overwrite-existing >/dev/null; \
		expected_server=$$(KUBECONFIG="$$expected_kubeconfig" kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}'); \
		current_context=$$(kubectl config current-context); \
		current_server=$$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}'); \
		if [ -z "$$expected_server" ] || [ "$$current_server" != "$$expected_server" ]; then echo "Current kubectl context '$$current_context' does not point to $(AKS_NAME) in $(RESOURCE_GROUP) / $(SUBSCRIPTION_ID)"; exit 1; fi
	kubectl delete namespace "$(OPEN_SANDBOX_NAMESPACE)" --ignore-not-found
	helm uninstall opensandbox-controller -n opensandbox-system || true
	kubectl delete namespace opensandbox-system --ignore-not-found

infra-delete:
	$(call reject_env_var,RESOURCE_GROUP,deletion)
	$(call reject_env_var,SUBSCRIPTION_ID,deletion)
	$(call require_cli_or_config,RESOURCE_GROUP)
	$(call require_cli_or_config,SUBSCRIPTION_ID)
	$(call confirm_var,RESOURCE_GROUP,delete infrastructure)
	$(call confirm_var,SUBSCRIPTION_ID,delete infrastructure)
	@current_subscription=$$(az account show --query id -o tsv); \
		if [ "$$current_subscription" != "$(SUBSCRIPTION_ID)" ]; then echo "Current Azure subscription '$$current_subscription' does not match $(SUBSCRIPTION_ID)"; exit 1; fi
	az group delete --name "$(RESOURCE_GROUP)" --subscription "$(SUBSCRIPTION_ID)" --yes --no-wait
