SHELL := /bin/bash

LOCAL_CONFIG ?= .make.env
LOCAL_CONFIG_PATH := $(abspath $(LOCAL_CONFIG))
REPO_ROOT := $(shell git rev-parse --show-toplevel 2>/dev/null)
ifneq ($(words $(LOCAL_CONFIG)),1)
$(error LOCAL_CONFIG must be a single path without whitespace)
endif
ifneq ($(wildcard $(LOCAL_CONFIG)),)
ifeq ($(shell test -L '$(LOCAL_CONFIG)' && echo yes),yes)
$(error Refusing to include symlinked LOCAL_CONFIG $(LOCAL_CONFIG))
endif
ifeq ($(REPO_ROOT),)
-include $(LOCAL_CONFIG)
else
LOCAL_CONFIG_REL := $(patsubst $(REPO_ROOT)/%,%,$(LOCAL_CONFIG_PATH))
ifeq ($(LOCAL_CONFIG_REL),$(LOCAL_CONFIG_PATH))
-include $(LOCAL_CONFIG)
else ifeq ($(shell git -C '$(REPO_ROOT)' check-ignore -q -- '$(LOCAL_CONFIG_REL)' && echo yes),yes)
-include $(LOCAL_CONFIG)
else
$(error Refusing to include unignored repo local config $(LOCAL_CONFIG_REL); add it to .gitignore or use LOCAL_CONFIG outside the repo)
endif
endif
endif
export OPEN_SANDBOX_API_KEY

RESOURCE_GROUP ?= rg-opensandbox-kata
SUBSCRIPTION_ID ?=
LOCATION ?= eastus
AKS_NAME ?= osb-kata-aks
ACR_NAME ?=
NODE_VM_SIZE ?= Standard_D4s_v3
NODE_COUNT ?= 3
ASSIGN_ACR_PULL_ROLE ?= true
ACR_ADMIN_USER_ENABLED ?= false
OPEN_SANDBOX_NAMESPACE ?= opensandbox
OPEN_SANDBOX_CONTROLLER_VERSION ?= 0.1.0
SERVER_IMAGE_NAME ?= opensandbox-kata-server
SERVER_IMAGE_TAG ?= latest
SANDBOX_IMAGE ?= python:3.12-slim
SERVER_PORT ?= 8080

ACR_LOGIN_SERVER := $(ACR_NAME).azurecr.io
SERVER_IMAGE := $(ACR_LOGIN_SERVER)/$(SERVER_IMAGE_NAME):$(SERVER_IMAGE_TAG)

.PHONY: all local-config print-config check-tools check-vars check-api-key infra-deploy aks-credentials acr-login image-build image-push controller-install k8s-deploy smoke-test status clean-k8s infra-delete _all _print-config _infra-deploy _aks-credentials _acr-login _image-build _image-push _controller-install _k8s-deploy _smoke-test

all: local-config
	@$(MAKE) --no-print-directory LOCAL_CONFIG="$(LOCAL_CONFIG)" _all

_all: check-tools check-api-key _infra-deploy _aks-credentials _acr-login _image-build _image-push _controller-install _k8s-deploy _smoke-test

local-config:
	@set -euo pipefail; \
		file="$(LOCAL_CONFIG)"; \
		case "$$file" in *[!A-Za-z0-9_./-]*) echo "LOCAL_CONFIG contains unsupported characters; use letters, numbers, dot, slash, underscore, or dash"; exit 1 ;; esac; \
		if [ -L "$$file" ]; then echo "Refusing to use symlinked LOCAL_CONFIG $$file"; exit 1; fi; \
		repo_root=$$(git rev-parse --show-toplevel 2>/dev/null || true); \
		if [ -n "$$repo_root" ]; then \
			case "$$file" in /*) config_path="$$file" ;; *) config_path="$$PWD/$$file" ;; esac; \
			case "$$config_path" in "$$repo_root"/*) \
				rel_path="$${config_path#"$$repo_root"/}"; \
				if git -C "$$repo_root" ls-files --error-unmatch -- "$$rel_path" >/dev/null 2>&1; then \
					echo "Refusing to write local config to tracked file $$rel_path"; \
					exit 1; \
				fi; \
				if ! git -C "$$repo_root" check-ignore -q -- "$$rel_path"; then \
					echo "Refusing to write secrets to unignored repo path $$rel_path; add it to .gitignore or use LOCAL_CONFIG outside the repo"; \
					exit 1; \
				fi; \
			;; esac; \
		fi; \
		changed=0; \
		if [ ! -f "$$file" ]; then \
			umask 077; \
			{ \
				echo '# Local environment config generated by make local-config'; \
				echo '# This file is intentionally ignored by git.'; \
			} > "$$file"; \
			changed=1; \
		fi; \
		chmod 600 "$$file"; \
		suffix=$$(date +%m%d%H%M | tr -d '\n'); \
		acr_suffix=$$(date +%m%d%H%M%S | tr -d '\n')$$(od -An -tx1 -N3 /dev/urandom | tr -d ' \n'); \
		api_key=$$(od -An -tx1 -N32 /dev/urandom | tr -d ' \n'); \
		current_subscription=$$(az account show --query id -o tsv 2>/dev/null || true); \
		value_for() { \
			origin="$$1"; \
			current="$$2"; \
			fallback="$$3"; \
			case "$$origin" in environment|"command line") printf '%s' "$$current" ;; *) printf '%s' "$$fallback" ;; esac; \
		}; \
		add_if_missing() { \
			key="$$1"; \
			line="$$2"; \
			if ! grep -Eq "^(export[[:space:]]+)?$$key[[:space:]]*([?:+]?=|=)" "$$file"; then \
				printf '%s\n' "$$line" >> "$$file"; \
				changed=1; \
			fi; \
		}; \
		location=$$(value_for '$(origin LOCATION)' '$(LOCATION)' 'eastus'); \
		resource_group=$$(value_for '$(origin RESOURCE_GROUP)' '$(RESOURCE_GROUP)' "rg-opensandbox-kata-$$suffix"); \
		subscription_id=$$(value_for '$(origin SUBSCRIPTION_ID)' '$(SUBSCRIPTION_ID)' "$$current_subscription"); \
		aks_name=$$(value_for '$(origin AKS_NAME)' '$(AKS_NAME)' "osb-kata-$$suffix"); \
		acr_name=$$(value_for '$(origin ACR_NAME)' '$(ACR_NAME)' "osbkata$$acr_suffix"); \
		api_key=$$(value_for '$(origin OPEN_SANDBOX_API_KEY)' '$(OPEN_SANDBOX_API_KEY)' "$$api_key"); \
		add_if_missing LOCATION "LOCATION ?= $$location"; \
		add_if_missing RESOURCE_GROUP "RESOURCE_GROUP ?= $$resource_group"; \
		if [ -n "$$subscription_id" ]; then add_if_missing SUBSCRIPTION_ID "SUBSCRIPTION_ID ?= $$subscription_id"; fi; \
		add_if_missing AKS_NAME "AKS_NAME ?= $$aks_name"; \
		add_if_missing ACR_NAME "ACR_NAME ?= $$acr_name"; \
		add_if_missing NODE_VM_SIZE 'NODE_VM_SIZE ?= Standard_D4s_v3'; \
		add_if_missing NODE_COUNT 'NODE_COUNT ?= 3'; \
		add_if_missing ASSIGN_ACR_PULL_ROLE 'ASSIGN_ACR_PULL_ROLE ?= true'; \
		add_if_missing ACR_ADMIN_USER_ENABLED 'ACR_ADMIN_USER_ENABLED ?= false'; \
		add_if_missing OPEN_SANDBOX_NAMESPACE 'OPEN_SANDBOX_NAMESPACE ?= opensandbox'; \
		add_if_missing OPEN_SANDBOX_CONTROLLER_VERSION 'OPEN_SANDBOX_CONTROLLER_VERSION ?= 0.1.0'; \
		add_if_missing SERVER_IMAGE_NAME 'SERVER_IMAGE_NAME ?= opensandbox-kata-server'; \
		add_if_missing SERVER_IMAGE_TAG 'SERVER_IMAGE_TAG ?= latest'; \
		add_if_missing SANDBOX_IMAGE 'SANDBOX_IMAGE ?= python:3.12-slim'; \
		add_if_missing SERVER_PORT 'SERVER_PORT ?= 8080'; \
		add_if_missing OPEN_SANDBOX_API_KEY "OPEN_SANDBOX_API_KEY ?= $$api_key"; \
		if ! grep -Eq '^export[[:space:]]+OPEN_SANDBOX_API_KEY([[:space:]]|$$)' "$$file"; then \
			echo 'export OPEN_SANDBOX_API_KEY' >> "$$file"; \
			changed=1; \
		fi; \
		if [ "$$changed" -eq 1 ]; then \
			echo "Updated $$file"; \
		else \
			echo "Using $$file"; \
		fi

print-config: local-config
	@$(MAKE) --no-print-directory -f $(firstword $(MAKEFILE_LIST)) LOCAL_CONFIG="$(LOCAL_CONFIG)" _print-config

.PHONY: _print-config
_print-config:
	@echo "LOCAL_CONFIG=$(LOCAL_CONFIG)"
	@echo "RESOURCE_GROUP=$(RESOURCE_GROUP)"
	@echo "SUBSCRIPTION_ID=$(SUBSCRIPTION_ID)"
	@echo "LOCATION=$(LOCATION)"
	@echo "AKS_NAME=$(AKS_NAME)"
	@echo "ACR_NAME=$(ACR_NAME)"
	@echo "NODE_VM_SIZE=$(NODE_VM_SIZE)"
	@echo "NODE_COUNT=$(NODE_COUNT)"
	@echo "ASSIGN_ACR_PULL_ROLE=$(ASSIGN_ACR_PULL_ROLE)"
	@echo "ACR_ADMIN_USER_ENABLED=$(ACR_ADMIN_USER_ENABLED)"
	@echo "OPEN_SANDBOX_NAMESPACE=$(OPEN_SANDBOX_NAMESPACE)"
	@echo "SERVER_IMAGE=$(SERVER_IMAGE)"

check-tools:
	@command -v az >/dev/null || (echo "az is required"; exit 1)
	@command -v kubectl >/dev/null || (echo "kubectl is required"; exit 1)
	@command -v helm >/dev/null || (echo "helm is required"; exit 1)
	@command -v docker >/dev/null || (echo "docker is required"; exit 1)
	@command -v python3 >/dev/null || (echo "python3 is required"; exit 1)
	@command -v curl >/dev/null || (echo "curl is required"; exit 1)

check-vars:
	@test -n "$(ACR_NAME)" || (echo "ACR_NAME is required and must be globally unique"; exit 1)
	@if [ "$(ASSIGN_ACR_PULL_ROLE)" = "false" ] && [ "$(ACR_ADMIN_USER_ENABLED)" != "true" ]; then \
		echo "ACR_ADMIN_USER_ENABLED=true is required when ASSIGN_ACR_PULL_ROLE=false"; \
		exit 1; \
	fi

check-api-key:
	@test -n "$${OPEN_SANDBOX_API_KEY}" || (echo "OPEN_SANDBOX_API_KEY is required"; exit 1)

infra-deploy: local-config
	@$(MAKE) --no-print-directory LOCAL_CONFIG="$(LOCAL_CONFIG)" _infra-deploy

_infra-deploy: check-vars
	az group create --name "$(RESOURCE_GROUP)" --location "$(LOCATION)"
	az deployment group create \
		--resource-group "$(RESOURCE_GROUP)" \
		--template-file infra/main.bicep \
		--parameters aksName="$(AKS_NAME)" acrName="$(ACR_NAME)" location="$(LOCATION)" nodeVmSize="$(NODE_VM_SIZE)" nodeCount=$(NODE_COUNT) assignAcrPullRole=$(ASSIGN_ACR_PULL_ROLE) acrAdminUserEnabled=$(ACR_ADMIN_USER_ENABLED)

aks-credentials: local-config
	@$(MAKE) --no-print-directory LOCAL_CONFIG="$(LOCAL_CONFIG)" _aks-credentials

_aks-credentials:
	az aks get-credentials --resource-group "$(RESOURCE_GROUP)" --name "$(AKS_NAME)" --overwrite-existing

acr-login: local-config
	@$(MAKE) --no-print-directory LOCAL_CONFIG="$(LOCAL_CONFIG)" _acr-login

_acr-login: check-vars
	@az acr show --name "$(ACR_NAME)" --query loginServer -o tsv >/dev/null

image-build: local-config
	@$(MAKE) --no-print-directory LOCAL_CONFIG="$(LOCAL_CONFIG)" _image-build

_image-build: check-vars
	docker build -t "$(SERVER_IMAGE)" -f examples/opensandbox-kata/server.Dockerfile .

image-push: local-config
	@$(MAKE) --no-print-directory LOCAL_CONFIG="$(LOCAL_CONFIG)" _image-push

_image-push: check-vars
	@set -euo pipefail; \
		login_server=$$(az acr show --name "$(ACR_NAME)" --query loginServer -o tsv); \
		test -n "$$login_server"; \
		test "$(ACR_LOGIN_SERVER)" = "$$login_server"; \
		docker_config=$$(mktemp -d); \
		chmod 700 "$$docker_config"; \
		trap 'DOCKER_CONFIG="$$docker_config" docker logout "'"$$login_server"'" >/dev/null 2>&1 || true; rm -rf "$$docker_config"' EXIT; \
		token=$$(az acr login --name "$(ACR_NAME)" --expose-token --query accessToken -o tsv); \
		test -n "$$token"; \
		DOCKER_CONFIG="$$docker_config" docker login "$$login_server" --username 00000000-0000-0000-0000-000000000000 --password-stdin <<< "$$token"; \
		DOCKER_CONFIG="$$docker_config" docker push "$(SERVER_IMAGE)"

controller-install: local-config
	@$(MAKE) --no-print-directory LOCAL_CONFIG="$(LOCAL_CONFIG)" _controller-install

_controller-install:
	helm upgrade --install opensandbox-controller \
		https://github.com/opensandbox-group/OpenSandbox/releases/download/helm/opensandbox-controller/$(OPEN_SANDBOX_CONTROLLER_VERSION)/opensandbox-controller-$(OPEN_SANDBOX_CONTROLLER_VERSION).tgz \
		--namespace opensandbox-system \
		--create-namespace
	kubectl wait --for=condition=Established crd/batchsandboxes.sandbox.opensandbox.io --timeout=180s
	kubectl wait --for=condition=Established crd/pools.sandbox.opensandbox.io --timeout=180s
	kubectl wait --for=condition=ready pod -l control-plane=controller-manager -n opensandbox-system --timeout=180s
	kubectl get runtimeclass kata-vm-isolation

k8s-deploy: local-config
	@$(MAKE) --no-print-directory LOCAL_CONFIG="$(LOCAL_CONFIG)" _k8s-deploy

_k8s-deploy: check-vars check-api-key
	kubectl create namespace "$(OPEN_SANDBOX_NAMESPACE)" --dry-run=client -o yaml | kubectl apply -f -
	kubectl -n "$(OPEN_SANDBOX_NAMESPACE)" create serviceaccount opensandbox-server --dry-run=client -o yaml | kubectl apply -f -
	kubectl -n "$(OPEN_SANDBOX_NAMESPACE)" create secret generic opensandbox-server \
		--from-literal=api-key="$${OPEN_SANDBOX_API_KEY}" \
		--dry-run=client -o yaml | kubectl apply -f -
	@if [ "$(ASSIGN_ACR_PULL_ROLE)" = "false" ] && [ "$(ACR_ADMIN_USER_ENABLED)" = "true" ]; then \
		set -euo pipefail; \
		password=$$(az acr credential show --name "$(ACR_NAME)" --query 'passwords[0].value' -o tsv); \
		test -n "$$password"; \
		kubectl delete secret acr-pull -n "$(OPEN_SANDBOX_NAMESPACE)" --ignore-not-found; \
		printf '%s' "$$password" | REGISTRY="$(ACR_LOGIN_SERVER)" USERNAME="$(ACR_NAME)" NAMESPACE="$(OPEN_SANDBOX_NAMESPACE)" python3 -c 'import base64,json,os,sys; u=os.environ["USERNAME"]; p=sys.stdin.read(); r=os.environ["REGISTRY"]; ns=os.environ["NAMESPACE"]; auth=base64.b64encode(f"{u}:{p}".encode()).decode(); cfg={"auths":{r:{"username":u,"password":p,"auth":auth}}}; data=base64.b64encode(json.dumps(cfg,separators=(",",":")).encode()).decode(); print(f"apiVersion: v1\nkind: Secret\nmetadata:\n  name: acr-pull\n  namespace: {ns}\ntype: kubernetes.io/dockerconfigjson\ndata:\n  .dockerconfigjson: {data}\n")' | kubectl create -f -; \
		kubectl -n "$(OPEN_SANDBOX_NAMESPACE)" patch serviceaccount opensandbox-server \
			--type merge \
			--patch '{"imagePullSecrets":[{"name":"acr-pull"}]}'; \
	fi
	sed \
		-e 's|__NAMESPACE__|$(OPEN_SANDBOX_NAMESPACE)|g' \
		examples/opensandbox-kata/config/sandbox.toml | kubectl -n "$(OPEN_SANDBOX_NAMESPACE)" create configmap opensandbox-server-config \
		--from-file=sandbox.toml=/dev/stdin \
		--dry-run=client -o yaml | kubectl apply -f -
	sed \
		-e 's|__SERVER_IMAGE__|$(SERVER_IMAGE)|g' \
		-e 's|__NAMESPACE__|$(OPEN_SANDBOX_NAMESPACE)|g' \
		examples/opensandbox-kata/k8s/opensandbox-server.yaml | kubectl apply -f -
	kubectl rollout restart deployment/opensandbox-server -n "$(OPEN_SANDBOX_NAMESPACE)"
	kubectl rollout status deployment/opensandbox-server -n "$(OPEN_SANDBOX_NAMESPACE)" --timeout=180s

smoke-test: local-config
	@$(MAKE) --no-print-directory LOCAL_CONFIG="$(LOCAL_CONFIG)" _smoke-test

_smoke-test: check-api-key
	kubectl -n "$(OPEN_SANDBOX_NAMESPACE)" port-forward svc/opensandbox-server $(SERVER_PORT):8080 >/tmp/opensandbox-kata-port-forward.log 2>&1 & echo $$! > /tmp/opensandbox-kata-port-forward.pid
	set -e; \
		trap 'kill $$(cat /tmp/opensandbox-kata-port-forward.pid) >/dev/null 2>&1 || true' EXIT; \
		for i in {1..30}; do curl -fsS http://localhost:$(SERVER_PORT)/health >/dev/null && break || sleep 1; done; \
		curl -fsS http://localhost:$(SERVER_PORT)/health >/dev/null; \
		python3 -m venv .venv; \
		. .venv/bin/activate; \
		pip install -q -r examples/opensandbox-kata/requirements.txt; \
		OPEN_SANDBOX_DOMAIN=localhost:$(SERVER_PORT) OPEN_SANDBOX_API_KEY="$${OPEN_SANDBOX_API_KEY}" SANDBOX_IMAGE="$(SANDBOX_IMAGE)" VERIFY_KATA_WITH_KUBECTL=1 OPEN_SANDBOX_NAMESPACE="$(OPEN_SANDBOX_NAMESPACE)" python examples/opensandbox-kata/app.py

status:
	kubectl get runtimeclass
	kubectl get pods -n opensandbox-system
	kubectl get pods -n "$(OPEN_SANDBOX_NAMESPACE)" -o wide
	kubectl get batchsandboxes -n "$(OPEN_SANDBOX_NAMESPACE)" || true

clean-k8s:
	@if [ "$(origin AKS_NAME)" = "environment" ]; then echo "For cleanup, pass AKS_NAME explicitly on the make command line or store it in $(LOCAL_CONFIG); environment values are not accepted"; exit 1; fi
	@if [ "$(origin RESOURCE_GROUP)" = "environment" ]; then echo "For cleanup, pass RESOURCE_GROUP explicitly on the make command line or store it in $(LOCAL_CONFIG); environment values are not accepted"; exit 1; fi
	@if [ "$(origin SUBSCRIPTION_ID)" = "environment" ]; then echo "For cleanup, pass SUBSCRIPTION_ID explicitly on the make command line or store it in $(LOCAL_CONFIG); environment values are not accepted"; exit 1; fi
	@if [ "$(origin OPEN_SANDBOX_NAMESPACE)" = "environment" ]; then echo "For cleanup, pass OPEN_SANDBOX_NAMESPACE explicitly on the make command line or store it in $(LOCAL_CONFIG); environment values are not accepted"; exit 1; fi
	@if [ "$(origin AKS_NAME)" != "command line" ] && ! grep -Eq '^(export[[:space:]]+)?AKS_NAME[[:space:]]*([?:+]?=|=)' "$(LOCAL_CONFIG)" 2>/dev/null; then echo "$(LOCAL_CONFIG) is missing AKS_NAME; run make local-config or pass AKS_NAME explicitly on the make command line"; exit 1; fi
	@if [ "$(origin RESOURCE_GROUP)" != "command line" ] && ! grep -Eq '^(export[[:space:]]+)?RESOURCE_GROUP[[:space:]]*([?:+]?=|=)' "$(LOCAL_CONFIG)" 2>/dev/null; then echo "$(LOCAL_CONFIG) is missing RESOURCE_GROUP; run make local-config or pass RESOURCE_GROUP explicitly on the make command line"; exit 1; fi
	@if [ "$(origin SUBSCRIPTION_ID)" != "command line" ] && ! grep -Eq '^(export[[:space:]]+)?SUBSCRIPTION_ID[[:space:]]*([?:+]?=|=)' "$(LOCAL_CONFIG)" 2>/dev/null; then echo "$(LOCAL_CONFIG) is missing SUBSCRIPTION_ID; run make local-config or pass SUBSCRIPTION_ID explicitly on the make command line"; exit 1; fi
	@if [ "$(origin OPEN_SANDBOX_NAMESPACE)" != "command line" ] && ! grep -Eq '^(export[[:space:]]+)?OPEN_SANDBOX_NAMESPACE[[:space:]]*([?:+]?=|=)' "$(LOCAL_CONFIG)" 2>/dev/null; then echo "$(LOCAL_CONFIG) is missing OPEN_SANDBOX_NAMESPACE; run make local-config or pass OPEN_SANDBOX_NAMESPACE explicitly on the make command line"; exit 1; fi
	@if [ "$(CONFIRM_AKS_NAME)" != "$(AKS_NAME)" ]; then echo "Set CONFIRM_AKS_NAME=$(AKS_NAME) to clean Kubernetes resources"; exit 1; fi
	@if [ "$(CONFIRM_RESOURCE_GROUP)" != "$(RESOURCE_GROUP)" ]; then echo "Set CONFIRM_RESOURCE_GROUP=$(RESOURCE_GROUP) to clean Kubernetes resources"; exit 1; fi
	@if [ "$(CONFIRM_SUBSCRIPTION_ID)" != "$(SUBSCRIPTION_ID)" ]; then echo "Set CONFIRM_SUBSCRIPTION_ID=$(SUBSCRIPTION_ID) to clean Kubernetes resources"; exit 1; fi
	@if [ "$(CONFIRM_OPEN_SANDBOX_NAMESPACE)" != "$(OPEN_SANDBOX_NAMESPACE)" ]; then echo "Set CONFIRM_OPEN_SANDBOX_NAMESPACE=$(OPEN_SANDBOX_NAMESPACE) to clean Kubernetes resources"; exit 1; fi
	@set -euo pipefail; \
		expected_kubeconfig=$$(mktemp); \
		trap 'rm -f "$$expected_kubeconfig"' EXIT; \
		az aks get-credentials --resource-group "$(RESOURCE_GROUP)" --name "$(AKS_NAME)" --subscription "$(SUBSCRIPTION_ID)" --file "$$expected_kubeconfig" --overwrite-existing >/dev/null; \
		expected_server=$$(KUBECONFIG="$$expected_kubeconfig" kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}'); \
		current_context=$$(kubectl config current-context); \
		current_server=$$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}'); \
		if [ -z "$$expected_server" ] || [ "$$current_server" != "$$expected_server" ]; then echo "Current kubectl context '$$current_context' does not point to $(AKS_NAME) in $(RESOURCE_GROUP) / $(SUBSCRIPTION_ID)"; exit 1; fi
	kubectl delete namespace "$(OPEN_SANDBOX_NAMESPACE)" --ignore-not-found
	helm uninstall opensandbox-controller -n opensandbox-system || true
	kubectl delete namespace opensandbox-system --ignore-not-found

infra-delete:
	@if [ "$(origin RESOURCE_GROUP)" = "environment" ]; then echo "For deletion, pass RESOURCE_GROUP explicitly on the make command line or store it in $(LOCAL_CONFIG); environment values are not accepted"; exit 1; fi
	@if [ "$(origin SUBSCRIPTION_ID)" = "environment" ]; then echo "For deletion, pass SUBSCRIPTION_ID explicitly on the make command line or store it in $(LOCAL_CONFIG); environment values are not accepted"; exit 1; fi
	@if [ "$(origin RESOURCE_GROUP)" != "command line" ] && ! grep -Eq '^(export[[:space:]]+)?RESOURCE_GROUP[[:space:]]*([?:+]?=|=)' "$(LOCAL_CONFIG)" 2>/dev/null; then echo "$(LOCAL_CONFIG) is missing RESOURCE_GROUP; run make local-config or pass RESOURCE_GROUP explicitly on the make command line"; exit 1; fi
	@if [ "$(origin SUBSCRIPTION_ID)" != "command line" ] && ! grep -Eq '^(export[[:space:]]+)?SUBSCRIPTION_ID[[:space:]]*([?:+]?=|=)' "$(LOCAL_CONFIG)" 2>/dev/null; then echo "$(LOCAL_CONFIG) is missing SUBSCRIPTION_ID; run make local-config or pass SUBSCRIPTION_ID explicitly on the make command line"; exit 1; fi
	@if [ "$(CONFIRM_RESOURCE_GROUP)" != "$(RESOURCE_GROUP)" ]; then echo "Set CONFIRM_RESOURCE_GROUP=$(RESOURCE_GROUP) to delete infrastructure"; exit 1; fi
	@if [ "$(CONFIRM_SUBSCRIPTION_ID)" != "$(SUBSCRIPTION_ID)" ]; then echo "Set CONFIRM_SUBSCRIPTION_ID=$(SUBSCRIPTION_ID) to delete infrastructure"; exit 1; fi
	@current_subscription=$$(az account show --query id -o tsv); \
		if [ "$$current_subscription" != "$(SUBSCRIPTION_ID)" ]; then echo "Current Azure subscription '$$current_subscription' does not match $(SUBSCRIPTION_ID)"; exit 1; fi
	az group delete --name "$(RESOURCE_GROUP)" --subscription "$(SUBSCRIPTION_ID)" --yes --no-wait
